config/routes.rb
SevenCareers::Engine.routes.draw do
  resources :jobs do
    resources :candidates, except: [:index, :edit, :update]
  end
end

app/models/seven_careers/candidate.rb
module SevenCareers
  class Candidate < ActiveRecord::Base
    include SevenCareers::Concerns::Candidate
  end
end

app/models/seven_careers/concerns/candidate.rb
module SevenCareers::Concerns::Candidate
  extend ActiveSupport::Concern
  included do
    belongs_to :job, :class_name => 'SevenCareers::Job'
    mount_uploader :resume, SevenCareers::ResumeUploader
    validates :name, presence: true
  end

  def image_size_validation
    if resume_path.size > 4.megabytes
      errors.add(:base, "Resume should be less than 4MB")
    end
  end
end

app/models/seven_careers/concerns/job.rb
module SevenCareers::Concerns::Job
  extend ActiveSupport::Concern
  included do
    has_many :candidates, :class_name => 'SevenCareers::Candidate'
  end
end

app/models/seven_careers/job.rb
module SevenCareers
  class Job < ActiveRecord::Base
    include SevenCareers::Concerns::Job
  end
end

app/controllers/seven_careers/application_controller.rb
module SevenCareers
  class ApplicationController < ActionController::Base
  end
end

app/controllers/seven_careers/candidates_controller.rb
require_dependency "seven_careers/application_controller"

module SevenCareers
  class CandidatesController < ApplicationController
    include SevenCareers::Concerns::CandidatesController
  end
end

app/controllers/seven_careers/concerns/candidates_controller.rb
module SevenCareers::Concerns::CandidatesController
  extend ActiveSupport::Concern

  included do
    before_action :set_job
    before_action :set_candidate, only: [:show, :destroy]
  end

  # GET /jobs/1/candidates/1
  # GET /jobs/1/candidates/1.json
  def show
  end

  # GET /jobs/1/candidates/new
  def new
    @candidate = SevenCareers::Candidate.new
  end

  # POST /jobs/1/candidates
  # POST /jobs/1/candidates.json
  def create
    @candidate = SevenCareers::Candidate.new(candidate_params)
    @job.candidates << @candidate
     respond_to do |format|
      if @job.save
        format.html { redirect_to session[:back_url] || @job, notice: "You applied to the job successfully." }
        format.json { render :show, status: :created, location: @candidate }
        flash[:success] = "You applied to the job successfully."
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1/candidates/1
  # DELETE /jobs/1/candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_resume
    @candidate = SevenCareers::Candidate.find(params[:id])
    SevenCareers::ResumeMailer.send_resume(@candidate).deliver_now
    redirect_to :back, notice: 'Resume mailed successfully.'
    # format.html {redirect_to(:back, notice: 'Resume mailed successfully.')}
  end


  private

  def set_job
    @job = SevenCareers::Job.find(params[:job_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_candidate
    @candidate = SevenCareers::Candidate.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def candidate_params
    params.require(:candidate).permit(:name, :email, :phone, :resume, :status_id)
  end
end

app/controllers/seven_careers/concerns/jobs_controller.rb
module SevenCareers::Concerns::JobsController
  extend ActiveSupport::Concern

  included do
    before_action :set_job, only: [:show, :edit, :update, :destroy]
  end

  def index
    @jobs = SevenCareers::Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = SevenCareers::Job.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = SevenCareers::Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = SevenCareers::Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def apply
    @job = SevenCareers::Job.find(params[:id])
    session[:apply_job_id] = @job.id
    redirect_to new_candidate_url
  end

  def show_applied_candidates
    @job = SevenCareers::Job.find(params[:id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = SevenCareers::Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:title, :description)
  end
end

app/controllers/seven_careers/jobs_controller.rb
require_dependency "seven_careers/application_controller"

module SevenCareers
  class JobsController < ApplicationController
    include SevenCareers::Concerns::JobsController
  end
end

app/helpers/seven_careers/application_helper.rb
module SevenCareers
  module ApplicationHelper
  end
end

app/helpers/seven_careers/candidate_statuses_helper.rb
module SevenCareers
  module CandidateStatusesHelper
  end
end

app/helpers/seven_careers/candidates_helper.rb
module SevenCareers
  module CandidatesHelper
  end
end

app/helpers/seven_careers/jobs_helper.rb
module SevenCareers
  module JobsHelper
  end
end

app/views/seven_careers/candidates/_form.html.erb
<%= form_for([@job, @candidate], :html => {:multipart => true}) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    Name <%= f.text_field :name %>
    Email <%= f.email_field :email %>
    Phone <%= f.phone_field :phone %>
    Resume <%= f.file_field :resume %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seven_careers/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', @job %>

app/views/seven_careers/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "download resume", @candidate.resume.url %>

<%= link_to 'Back', job_url(@job) %>

app/views/seven_careers/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= fields_for "job" do |job| %>
        Title <%= job.text_field :title %>
        Description <%= job.text_area :description %>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seven_careers/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/seven_careers/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Applied Candidates</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.candidates.length %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/seven_careers/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/seven_careers/jobs/show.html.erb
<p id="notice"><%= notice %></p>

Job Title <%= @job.title %>
Description <%= @job.description %>

<p>Candidates: </p>
<% if @job.candidates.any? %>
    <table>
      <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @job.candidates.each do |candidate| %>
          <tr>
            <td><span><%= candidate.name %></span></td>
            <td><%= link_to 'Show', job_candidate_url(@job, candidate) %></td>
            <td><%= link_to 'Destroy', job_candidate_url(@job, candidate), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <p>There's no candidates.</p>
<% end %>

<%= link_to "apply", new_job_candidate_path(@job) %>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/seven_careers/jobs/show_applied_candidates.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candidates for <%= @job.title %> vacancy.</h1>
<% if @job.candidates.exists? %>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Resume</th>
    <th>Applied At</th>
    <th>Status</th>
    <th></th>

  </tr>
  </thead>

  <tbody>




  <% @job.candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.phone %></td>
        <td><%= link_to "Download Resume", candidate.resume.url %></td>
        <td><%= candidate.created_at %></td>
        <td>
          <%= form_for(candidate) do |status| %>
              <%= collection_select :candidate, :status_id, SevenCareers::CandidateStatus.all, :id, :name, {:include_blank => true, :selected => candidate.status_id}, {:onchange => 'this.form.submit();' }  %>
          <% end  %>

        </td>
        <td><%= link_to "Send Resume", candidate_send_resume_url(:id => candidate.id) %></td>




      </tr>
  <% end %>
  </tbody>
</table>

<% else %>
    No candidates applied fot this job.

<% end %>